[build]
  publish = "public"
  command = "pnpm build"

  [build.environment]
    HUGO_VERSION = "0.120.3"

[context.production.environment]
  HUGO_ENV           = "production"
  HUGO_ENABLEGITINFO = "true"